services:
  irods-server:
    container_name: irods-server
    image: "ghcr.io/wtsi-npg/ub-18.04-irods-${IRODS_VERSION:-4.2.12}:${DOCKER_TAG:-latest}"
    restart: always
    ports:
      - "1247:1247"
      - "20000-20199:20000-20199"
